### ISSUE TITLE
Support Sonar 6.5

### ISSUE THREAD

**Issue by K3UL** [ZoeThivet/sonar-l10n-fr#10]
Is there plan to add support for SonarQube 6 (current 6.5) ?

**Comment by ZoeThivet** [comment]
Work in progress. Those days I'm trying to make some time to translate the LTS version.
Any help appreciated, feel free to make a pull request

**Comment by ZoeThivet** [comment]
We're almost there!
French pack plugin for version 6.7.3:
https://github.com/ZoeThivet/sonar-l10n-fr/releases/tag/1.15

**Comment by ZoeThivet** [comment]
Done!
