### ISSUE TITLE
traduire "Projects"

### ISSUE THREAD

**Issue by JulienAMOURIQ** [ZoeThivet/sonar-l10n-fr#12]
Bonjour,
Pourquoi pas "Projets" pour traduire Projects" ?
Cordialement
Julien

**Comment by ZoeThivet** [comment]
Ce terme est déjà traduit (pour la version 5.3 en tous cas).
Voir [ici](https://github.com/ZoeThivet/sonar-l10n-fr/commit/94bb565788ff6128de1e0d8988711a11d1b00e9c#diff-fa38e33dbbbb0cf0f17e9ad0e9686c86)
