### ISSUE TITLE
traduire "and worse"

### ISSUE THREAD

**Issue by JulienAMOURIQ** [ZoeThivet/sonar-l10n-fr#13]
Bonjour,
Que dites-vous de "et pire" pour "and worse"
Coordialement
Julien

**Comment by ZoeThivet** [comment]
Bonjour,
Cela sera réglé dans la prochaine version (voir [ce fichier](https://github.com/ZoeThivet/sonar-l10n-fr/blob/master/src/main/resources/org/sonar/l10n/core_fr.properties), ligne 91)
Il semblerait que "and worse" soit un texte présent à partir de la V6, or le plugin n'est pour le moment adapté qu'à la V5.
