### ISSUE TITLE
traduire "Size"

### ISSUE THREAD

**Issue by JulienAMOURIQ** [ZoeThivet/sonar-l10n-fr#14]
Bonjour 
Que dites-vous de "Taille" pour "Size"
Cordialement
Julien

**Comment by ZoeThivet** [comment]
Bonjour,
Cela sera réglé dans la prochaine version (voir [ce fichier](https://github.com/ZoeThivet/sonar-l10n-fr/blob/master/src/main/resources/org/sonar/l10n/core_fr.properties))
