### ISSUE TITLE
traduire "filter"

### ISSUE THREAD

**Issue by JulienAMOURIQ** [ZoeThivet/sonar-l10n-fr#15]
Bonjour,
Que dites-vous de 'Filtre' pour 'Filter' ?
Cordialement
Julien

**Comment by ZoeThivet** [comment]
Bonjour,
Cela sera réglé dans la prochaine version (voir [ce fichier](https://github.com/ZoeThivet/sonar-l10n-fr/blob/master/src/main/resources/org/sonar/l10n/core_fr.properties))
