### ISSUE TITLE
Typo in version number [1.5 vs 1.15]

### ISSUE THREAD

**Issue by mildis** [ZoeThivet/sonar-l10n-fr#21]
The pom.xml state version 1.5 whereas it is supposed to be 1.15.
It confuses SQ by always suggesting to install a new version (1.15 beeing greater than 1.5)

Suggested workaround : publish version 1.15.1 with a coherent version number internally and externally.

**Comment by rtdean** [comment]
Agreed, just came across this tonight after upgrading to 1.15.

**Comment by rtdean** [comment]
Actually, I see that you've updated the pom to 1.15.1.  Any chance you could tag and build a release?

**Comment by ZoeThivet** [comment]
Hello,

Thank you for your comments.
The error is fixed and will soon appear in the market place. If you wish, you can download the plugin and install it: https://github.com/ZoeThivet/sonar-l10n-en/releases/tag/1.15.1

Best regards
