### ISSUE TITLE
Typo on CodeSmell type

### ISSUE THREAD

**Issue by TPGEric** [ZoeThivet/sonar-l10n-fr#22]
Hi, 
there is a typo on code smell type called "Maubaise pratique" instead of Mauvaise Pratique, see picture below.
![image](https://user-images.githubusercontent.com/33157150/43196618-dc019582-9008-11e8-816b-2a11c25eb055.png)

Thanks

**Comment by ZoeThivet** [comment]
Hello,

Thank you for your comment.
The error is fixed and will soon appear in the marketplace. If you wish, you can download the plugin and install it manually: https://github.com/ZoeThivet/sonar-l10n-en/releases/tag/1.15.1

Best regards
