### ISSUE TITLE
Mauvaise traduction dans la partie filtre

### ISSUE THREAD

**Issue by tlouis974** [ZoeThivet/sonar-l10n-fr#23]
Bonjour,
Dans la partie filtre le texte est mal traduit : 
"Maubaise pratique" au lieu de "Mauvaise pratique"
 
![capture](https://user-images.githubusercontent.com/42175622/43774496-5516c900-9a5a-11e8-9d27-5e1ec9bf1b98.PNG)

**Comment by ZoeThivet** [comment]
Bonjour,

Merci pour votre commentaire.
C'est corrigé et cela paraîtra bientôt dans la marketplace. Si vous le souhaitez vous pouvez d'ores et déjà télécharger le plugin et l'installer manuellement : https://github.com/ZoeThivet/sonar-l10n-fr/releases/tag/1.15.1

Bien cordialement
